services:

  database:
    image: mysql:${MYSQL_VERSION:-8.0}-oracle
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-finalprojectcda}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER:-app}", "-p${MYSQL_PASSWORD:-!ChangeMe!}"]
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306:3306"


  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      mailpit:
        condition: service_started
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DATABASE:-finalprojectcda}?serverVersion=8.0"
      MAILER_DSN: smtp://mailpit:1025
    command: php -S 0.0.0.0:8000 -t public
 

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # interface web
      - "1025:1025" # serveur SMTP

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
